server:
  servlet:
    context-path: /example
  port: 8080
  shutdown: graceful

spring:
  application:
    name: xuchen93-framework-example
  data:
    redis:
      host: localhost
      port: 6379
      password: password
      database: 0
      timeout: 60s
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 0
          max-wait: 5s

xuchen93:
  framework:
    base:
      log-aspect:
        enable-log: true
        enable-stats: true
      method-stats:
        enable-consume: true
        consume-seconds: 300

    cache:
      caffeine:
        enable-cache-manager: true
        primary: true
        expire-after-write-seconds: 10
        expire-after-access-seconds: 3
      redis:
        enable: true
        enable-annotation-lock: true
        enable-lock-detail: true
        cache-manager:
          enable: true
          key-prefix: "example:cache:"
          primary: false
          expire-seconds: 300
    web:
      request-aspect:
        enable-log: true
        enable-stats: true
      enable-exception-advice: true
      enable-app-start-log: true
logging:
  pattern:
    console: "%boldMagenta(%d{yyyy-MM-dd HH:mm:ss.SSS}) | %highlight(%-5level) | %boldYellow(%-18t) | %boldGreen(%50.50logger{49}):%boldGreen(%-4.4line) | %msg%n"
